import { useState } from 'react';
import {
  pdf,
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from '@react-pdf/renderer';
import html2canvas from 'html2canvas';

import { hexToRgb, rgbToHsl } from '../utils/colourMath';
import { ROLE_COL, ROLE_DESC } from '../utils/autoRoles';
import { getColourName } from '../utils/colourNames';
import ExportTokensTab from './ExportTokensTab';
import PlatformExportSection from './PlatformExportSection';

// ─── Shared colour-data helper ────────────────────────────────────────────────
// All values derived from existing utils — no duplicated math.
function getColorData(hex, roles) {
  const { r, g, b } = hexToRgb(hex);
  const { h, s, l } = rgbToHsl(r, g, b);
  return {
    hex,
    r, g, b,
    h: Math.round(h),
    s: Math.round(s),
    l: Math.round(l),
    role: roles[hex] || null,
  };
}

// ─── Tailwind config generator ───────────────────────────────────────────────
function generateTailwindConfig(colors, roles, scales) {
  const roleOrder = ['Hero', 'Accent', 'Neutral', 'Background', 'Text'];
  const assignedRoles = roleOrder.filter(r => Object.values(roles).includes(r));

  const lines = [
    '// tailwind.config.js — generated by Palette Studio',
    'module.exports = {',
    '  theme: {',
    '    extend: {',
    '      colors: {',
  ];

  if (assignedRoles.length > 0) {
    lines.push('        // Core palette roles');
    assignedRoles.forEach(role => {
      const hex = Object.keys(roles).find(k => roles[k] === role);
      lines.push(`        'brand-${role.toLowerCase()}': '${hex.toLowerCase()}',`);
    });
    lines.push('');
  }

  lines.push('        // Full tint & shade scales');
  colors.forEach((hex, i) => {
    const role    = roles[hex];
    const varBase = role ? role.toLowerCase() : `color-${i + 1}`;
    const scale   = scales && scales[hex];
    if (!scale) return;
    lines.push(`        '${varBase}': {`);
    scale.forEach(s => {
      lines.push(`          ${s.step}: '${s.hex.toLowerCase()}',`);
    });
    lines.push('        },');
  });

  lines.push('      },');
  lines.push('    },');
  lines.push('  },');
  lines.push('};');

  return lines.join('\n');
}

// ─── CSS variables generator ──────────────────────────────────────────────────
function generateCSSVars(colors, roles, scales) {
  const date      = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const roleOrder = ['Hero', 'Accent', 'Neutral', 'Background', 'Text'];

  const lines = [
    ':root {',
    '  /* Palette Studio — Brand Colours */',
    `  /* Generated: ${date} */`,
    '',
  ];

  // Core palette (role-named variables — only if assigned)
  const assignedRoles = roleOrder.filter(r => Object.values(roles).includes(r));
  if (assignedRoles.length > 0) {
    lines.push('  /* Core palette */');
    const longest = Math.max(...assignedRoles.map(r => `--color-${r.toLowerCase()}`.length));
    assignedRoles.forEach(role => {
      const hex      = Object.keys(roles).find(k => roles[k] === role);
      const varName  = `--color-${role.toLowerCase()}`;
      const pad      = ' '.repeat(Math.max(1, longest - varName.length + 1));
      const name     = getColourName(hex);
      lines.push(`  ${varName}:${pad}${hex.toLowerCase()}; /* ${name} */`);
    });
    lines.push('');
  }

  // Full palette (all colours including unassigned)
  lines.push('  /* Full palette (all colours, including unassigned) */');
  colors.forEach((hex, i) => {
    const name      = getColourName(hex);
    const roleEntry = roles[hex] ? ` /* ${name} — ${roles[hex]} */` : ` /* ${name} */`;
    lines.push(`  --color-${i + 1}: ${hex.toLowerCase()};${roleEntry}`);
  });

  // Tint & shade scales — one block per colour
  if (scales && Object.keys(scales).length > 0) {
    lines.push('');
    lines.push('  /* Tint & shade scales (OKLCH-generated, perceptually uniform) */');
    colors.forEach((hex, i) => {
      const scale   = scales[hex];
      if (!scale) return;
      const role    = roles[hex];
      const varBase = role ? `--color-${role.toLowerCase()}` : `--color-${i + 1}`;
      lines.push('');
      lines.push(`  /* ${varBase} */`);
      scale.forEach(s => {
        lines.push(`  ${varBase}-${s.step}: ${s.hex.toLowerCase()};`);
      });
    });
  }

  lines.push('}');
  return lines.join('\n');
}

// ─── react-pdf styles ─────────────────────────────────────────────────────────
const S = StyleSheet.create({
  page: {
    paddingTop:    44,
    paddingBottom: 60,
    paddingLeft:   48,
    paddingRight:  48,
    fontFamily:    'Helvetica',
    fontSize:       9,
    color:         '#2a2420',
    backgroundColor: '#ffffff',
  },

  /* Header */
  headerRow: {
    flexDirection:  'row',
    justifyContent: 'space-between',
    alignItems:     'flex-end',
    marginBottom:    8,
  },
  mainTitle: {
    fontSize:    22,
    fontFamily:  'Helvetica-Bold',
    color:       '#1a1510',
  },
  subtitle: {
    fontSize:   10,
    color:      '#8a7a6a',
    marginTop:   2,
  },
  dateText: {
    fontSize: 8,
    color:    '#aaa9a6',
  },
  rule: {
    borderBottomWidth: 0.75,
    borderBottomColor: '#e4ddd4',
    marginBottom:      16,
  },

  /* Section */
  section: {
    marginBottom: 18,
  },
  sectionLabel: {
    fontSize:      7,
    fontFamily:    'Helvetica-Bold',
    letterSpacing:  1,
    color:         '#b8703a',
    marginBottom:   8,
  },

  /* Health score */
  scoreLarge: {
    fontSize:     26,
    fontFamily:   'Helvetica-Bold',
    marginBottom:  5,
  },
  scoreBarBg: {
    height:          8,
    backgroundColor: '#e4ddd4',
    borderRadius:    4,
    marginBottom:    5,
  },
  scoreBarFill: {
    height:       8,
    borderRadius: 4,
  },
  scoreSummary: {
    fontSize:   8,
    color:      '#6a5a4e',
    fontStyle:  'italic',
  },

  /* Swatch rows */
  swatchRow: {
    flexDirection:  'row',
    alignItems:     'flex-start',
    marginBottom:    9,
  },
  swatchRect: {
    width:        60,
    height:       40,
    borderRadius:  4,
    marginRight:  12,
    flexShrink:    0,
  },
  swatchInfo: {
    flex: 1.2,
  },
  swatchRoleDesc: {
    flex: 2,
    paddingLeft: 8,
  },
  hexCode: {
    fontSize:      11,
    fontFamily:    'Courier-Bold',
    color:         '#1a1510',
    marginBottom:   1,
  },
  colourNameLabel: {
    fontSize:      8,
    fontFamily:    'Helvetica-Oblique',
    color:         '#aaa9a6',
    marginBottom:  2,
  },
  colorValues: {
    fontSize:     8,
    color:        '#6a5a4e',
    marginBottom: 1,
  },
  roleBadge: {
    marginTop:         3,
    paddingVertical:    2,
    paddingHorizontal:  6,
    borderRadius:       3,
    alignSelf:         'flex-start',
  },
  roleBadgeText: {
    fontSize:      7,
    fontFamily:    'Helvetica-Bold',
    color:         '#ffffff',
    letterSpacing:  0.5,
  },
  unassigned: {
    fontSize:   8,
    color:      '#aaa9a6',
    marginTop:   3,
    fontStyle:  'italic',
  },
  roleDescText: {
    fontSize:    8,
    color:       '#6a5a4e',
    lineHeight:  1.4,
    marginTop:   2,
  },

  /* Tint/shade scale strip (in PDF) */
  scaleStripRow: {
    flexDirection:  'row',
    marginTop:       5,
    marginBottom:    2,
  },
  scaleChip: {
    width:        24,
    height:       14,
    marginRight:   2,
    borderRadius:  2,
  },
  scaleCaption: {
    fontSize:   7,
    color:      '#aaa9a6',
    fontStyle:  'italic',
    marginBottom: 4,
  },

  /* 60-30-10 */
  proportionBar: {
    flexDirection: 'row',
    height:         16,
    borderRadius:    4,
    overflow:       'hidden',
    marginBottom:    5,
  },
  proportionCaption: {
    fontSize: 8,
    color:    '#6a5a4e',
  },

  /* Issues */
  issueRow: {
    flexDirection:  'row',
    alignItems:     'flex-start',
    marginBottom:    4,
  },
  issueIcon: {
    fontSize:     8,
    marginRight:  5,
    marginTop:    1,
    width:        10,
  },
  issueTitle: {
    fontSize: 8,
    color:    '#4a3f35',
    flex:      1,
  },

  /* Footer (absolute position) */
  footer: {
    position: 'absolute',
    bottom:   32,
    left:     48,
    right:    48,
  },
  footerRule: {
    borderTopWidth: 0.5,
    borderTopColor: '#e4ddd4',
    marginBottom:    7,
  },
  footerRow: {
    flexDirection:  'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 7,
    color:    '#aaa9a6',
  },
});

// ─── PDF document component ───────────────────────────────────────────────────
function BrandGuidePDF({ colors, roles, issues, score, scales }) {
  const date       = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const scoreCol   = score >= 80 ? '#4caf7d' : score >= 60 ? '#e5a830' : '#d94f3d';
  const scoreSummary =
    score >= 80 ? 'Your palette is well balanced and ready to use.' :
    score >= 60 ? 'A few things to address before this palette is production-ready.' :
                  'This palette needs work — review the issues in Palette Studio.';

  const colorData  = colors.map(hex => getColorData(hex, roles));
  // Only show scale strips if at least one role is assigned (user has completed setup)
  const hasAnyRole = Object.keys(roles).length > 0;

  const bgHex   = Object.keys(roles).find(k => roles[k] === 'Background') || '#cccccc';
  const heroHex = Object.keys(roles).find(k => roles[k] === 'Hero')       || '#999999';
  const accHex  = Object.keys(roles).find(k => roles[k] === 'Accent')     || '#777777';
  const hasRoles = Object.values(roles).includes('Background') &&
                   (Object.values(roles).includes('Hero') || Object.values(roles).includes('Accent'));

  const badIssues   = issues.filter(i => i.type === 'warning' || i.type === 'critical');
  const shownIssues = badIssues.slice(0, 8);
  const extraCount  = badIssues.length - shownIssues.length;

  return (
    <Document>
      <Page size="A4" style={S.page}>

        {/* ── Header ───────────────────────────────────── */}
        <View style={S.headerRow}>
          <View>
            <Text style={S.mainTitle}>Palette Studio</Text>
            <Text style={S.subtitle}>Brand Colour Guide</Text>
          </View>
          <Text style={S.dateText}>{date}</Text>
        </View>
        <View style={S.rule} />

        {/* ── Health score ──────────────────────────────── */}
        <View style={S.section}>
          <Text style={S.sectionLabel}>PALETTE HEALTH</Text>
          <Text style={[S.scoreLarge, { color: scoreCol }]}>{score} / 100</Text>
          <View style={S.scoreBarBg}>
            <View style={[S.scoreBarFill, { width: `${score}%`, backgroundColor: scoreCol }]} />
          </View>
          <Text style={S.scoreSummary}>{scoreSummary}</Text>
        </View>

        {/* ── Swatches ──────────────────────────────────── */}
        <View style={S.section}>
          <Text style={S.sectionLabel}>YOUR COLOUR PALETTE</Text>
          {colorData.map((c, i) => {
            const scale = scales && scales[c.hex];
            return (
              <View key={i} style={{ marginBottom: 10 }}>
                {/* Main swatch row */}
                <View style={S.swatchRow}>
                  {/* Filled colour rectangle — actual swatch, not just text */}
                  <View style={[S.swatchRect, { backgroundColor: c.hex }]} />

                  {/* Values */}
                  <View style={S.swatchInfo}>
                    <Text style={S.hexCode}>{c.hex.toUpperCase()}</Text>
                    <Text style={S.colourNameLabel}>{getColourName(c.hex)}</Text>
                    <Text style={S.colorValues}>rgb({c.r}, {c.g}, {c.b})</Text>
                    <Text style={S.colorValues}>hsl({c.h}°, {c.s}%, {c.l}%)</Text>
                    {c.role ? (
                      <View style={[S.roleBadge, { backgroundColor: ROLE_COL[c.role] || '#888' }]}>
                        <Text style={S.roleBadgeText}>{c.role.toUpperCase()}</Text>
                      </View>
                    ) : (
                      <Text style={S.unassigned}>— unassigned</Text>
                    )}
                  </View>

                  {/* Role description */}
                  {c.role && (
                    <View style={S.swatchRoleDesc}>
                      <Text style={S.roleDescText}>{ROLE_DESC[c.role] || ''}</Text>
                    </View>
                  )}
                </View>

                {/* Compact scale strip — only when at least one role is assigned */}
                {hasAnyRole && scale && (
                  <View>
                    <View style={S.scaleStripRow}>
                      {scale.map(s => (
                        <View
                          key={s.step}
                          style={[S.scaleChip, { backgroundColor: s.hex }]}
                        />
                      ))}
                    </View>
                    <Text style={S.scaleCaption}>Tint &amp; shade scale — 100 to 900</Text>
                  </View>
                )}
              </View>
            );
          })}
        </View>

        {/* ── 60-30-10 proportion strip ─────────────────── */}
        <View style={S.section}>
          <Text style={S.sectionLabel}>COLOUR PROPORTION GUIDE</Text>
          {hasRoles ? (
            <>
              <View style={S.proportionBar}>
                <View style={{ flex: 60, backgroundColor: bgHex }} />
                <View style={{ flex: 30, backgroundColor: heroHex }} />
                <View style={{ flex: 10, backgroundColor: accHex }} />
              </View>
              <Text style={S.proportionCaption}>
                60% background  ·  30% brand  ·  10% accent
              </Text>
            </>
          ) : (
            <>
              <View style={S.proportionBar}>
                <View style={{ flex: 60, backgroundColor: '#d4cfc9' }} />
                <View style={{ flex: 30, backgroundColor: '#b8b0a8' }} />
                <View style={{ flex: 10, backgroundColor: '#9a9490' }} />
              </View>
              <Text style={S.proportionCaption}>
                Assign colour roles in Palette Studio to see your proportion guide
              </Text>
            </>
          )}
        </View>

        {/* ── Issues (only if present) ──────────────────── */}
        {shownIssues.length > 0 && (
          <View style={S.section}>
            <Text style={S.sectionLabel}>ISSUES TO ADDRESS</Text>
            {shownIssues.map((issue, i) => (
              <View key={i} style={S.issueRow}>
                <Text style={[S.issueIcon, { color: issue.type === 'critical' ? '#d94f3d' : '#e5a830' }]}>
                  {issue.type === 'critical' ? '●' : '▲'}
                </Text>
                <Text style={S.issueTitle}>{issue.title}</Text>
              </View>
            ))}
            {extraCount > 0 && (
              <Text style={{ fontSize: 8, color: '#b8703a', marginTop: 3 }}>
                + {extraCount} additional issue{extraCount !== 1 ? 's' : ''} — open Palette Studio to review
              </Text>
            )}
          </View>
        )}

        {/* ── Footer ───────────────────────────────────── */}
        <View style={S.footer} fixed>
          <View style={S.footerRule} />
          <View style={S.footerRow}>
            <Text style={S.footerText}>Created with Palette Studio</Text>
            <Text style={S.footerText}>palette-studio.app</Text>
          </View>
        </View>

      </Page>
    </Document>
  );
}

// ─── PNG hidden render component ─────────────────────────────────────────────
function buildPNGNode(colors, roles) {
  const SWATCH_W = 120;
  const SWATCH_GAP = 20;
  const PADDING = 20;
  const totalW = colors.length * (SWATCH_W + SWATCH_GAP) - SWATCH_GAP + PADDING * 2;

  const container = document.createElement('div');
  container.style.cssText = [
    'position:absolute',
    'left:-9999px',
    'top:0',
    `width:${totalW}px`,
    'height:260px',
    'background:#f5f2ed',
    `padding:${PADDING}px`,
    "font-family:'DM Mono',monospace",
    'box-sizing:border-box',
  ].join(';');

  // Header row
  const header = document.createElement('div');
  header.style.cssText = 'display:flex;align-items:baseline;gap:8px;margin-bottom:14px';

  const title = document.createElement('span');
  title.textContent = 'Palette Studio';
  title.style.cssText = "font-size:15px;font-weight:700;color:#1a1510;font-family:'Georgia',serif;letter-spacing:0.02em";

  const dateSep = document.createElement('span');
  dateSep.textContent = '—';
  dateSep.style.cssText = 'font-size:11px;color:#ccc5bc';

  const dateEl = document.createElement('span');
  dateEl.textContent = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  dateEl.style.cssText = 'font-size:10px;color:#9a8878';

  header.appendChild(title);
  header.appendChild(dateSep);
  header.appendChild(dateEl);
  container.appendChild(header);

  // Swatches row
  const row = document.createElement('div');
  row.style.cssText = 'display:flex;gap:20px';

  colors.forEach(hex => {
    const role    = roles[hex] || null;
    const roleCol = role ? (ROLE_COL[role] || '#888') : '#aaa9a6';

    const cell = document.createElement('div');
    cell.style.cssText = `display:flex;flex-direction:column;align-items:center;width:${SWATCH_W}px`;

    const box = document.createElement('div');
    box.style.cssText = [
      `width:${SWATCH_W}px`,
      'height:120px',
      `background:${hex}`,
      'border-radius:8px',
      'border:1px solid rgba(0,0,0,0.10)',
      'margin-bottom:7px',
      'box-sizing:border-box',
    ].join(';');

    const hexLabel = document.createElement('div');
    hexLabel.textContent = hex.toUpperCase();
    hexLabel.style.cssText = 'font-size:11px;font-weight:700;color:#1a1510;letter-spacing:0.05em;margin-bottom:3px;font-family:monospace';

    const roleLabel = document.createElement('div');
    roleLabel.textContent = role ? role.toUpperCase() : 'UNASSIGNED';
    roleLabel.style.cssText = `font-size:9px;font-weight:700;color:${roleCol};letter-spacing:0.07em`;

    cell.appendChild(box);
    cell.appendChild(hexLabel);
    cell.appendChild(roleLabel);
    row.appendChild(cell);
  });

  container.appendChild(row);
  return container;
}

// ─── Card shell component ─────────────────────────────────────────────────────
function ExportCard({ title, description, children }) {
  return (
    <div
      style={{
        background:    'var(--ps-bg-surface)',
        border:        '1px solid var(--ps-border)',
        borderRadius:  'var(--ps-radius-xl)',
        padding:       '20px 22px',
        display:       'flex',
        flexDirection: 'column',
        gap:           14,
        boxShadow:     'var(--ps-shadow-sm)',
      }}
    >
      <div>
        <div
          style={{
            fontFamily:   'var(--ps-font-ui)',
            fontSize:     'var(--ps-text-lg)',
            fontWeight:   700,
            color:        'var(--ps-text-primary)',
            marginBottom: 5,
          }}
        >
          {title}
        </div>
        <div
          style={{
            fontFamily: 'var(--ps-font-ui)',
            fontSize:   'var(--ps-text-sm)',
            color:      'var(--ps-text-secondary)',
            lineHeight: 1.55,
          }}
        >
          {description}
        </div>
      </div>
      {children}
    </div>
  );
}

function ActionBtn({ onClick, disabled, loading, loadingLabel, children, error }) {
  return (
    <div>
      <button
        onClick={onClick}
        disabled={disabled || loading}
        style={{
          background:    loading || disabled ? 'var(--ps-border)' : 'var(--ps-accent)',
          color:         loading || disabled ? 'var(--ps-text-tertiary)' : 'var(--ps-accent-text)',
          border:        'none',
          borderRadius:  'var(--ps-radius-md)',
          padding:       '9px 20px',
          fontFamily:    'var(--ps-font-ui)',
          fontSize:      'var(--ps-text-sm)',
          fontWeight:    500,
          cursor:        loading || disabled ? 'default' : 'pointer',
          letterSpacing: '.02em',
          transition:    'background .15s',
        }}
        onMouseEnter={e => { if (!disabled && !loading) e.currentTarget.style.background = 'var(--ps-accent-hover)'; }}
        onMouseLeave={e => { if (!disabled && !loading) e.currentTarget.style.background = 'var(--ps-accent)'; }}
      >
        {loading ? loadingLabel : children}
      </button>
      {error && (
        <div
          style={{
            fontFamily: 'var(--ps-font-ui)',
            marginTop:  8,
            fontSize:   'var(--ps-text-sm)',
            color:      'var(--ps-danger)',
            lineHeight: 1.5,
          }}
        >
          ⚠ {error}
        </div>
      )}
    </div>
  );
}

// ─── Main export tab ──────────────────────────────────────────────────────────
export default function ExportTab({ colors, roles, issues, score, scales, selectedFont }) {
  // PDF state
  const [pdfLoading, setPdfLoading] = useState(false);
  const [pdfError,   setPdfError]   = useState('');

  // CSS state — regenerated whenever colors/roles/scales change
  const [copied,    setCopied]    = useState(false);
  const cssOutput = generateCSSVars(colors, roles, scales);

  // PNG state
  const [pngLoading, setPngLoading] = useState(false);
  const [pngError,   setPngError]   = useState('');

  // Tailwind state
  const [twCopied, setTwCopied] = useState(false);

  // ── Handlers ───────────────────────────────────────────────────────────────

  const handlePDFDownload = async () => {
    setPdfLoading(true);
    setPdfError('');
    try {
      const blob = await pdf(
        <BrandGuidePDF colors={colors} roles={roles} issues={issues} score={score} scales={scales} />
      ).toBlob();
      const url = URL.createObjectURL(blob);
      const a   = document.createElement('a');
      a.href     = url;
      a.download = 'palette-studio-brand-guide.pdf';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (e) {
      setPdfError(
        'PDF generation failed. ' +
        (e.message || 'Please try again, or check the browser console for details.')
      );
    } finally {
      setPdfLoading(false);
    }
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(cssOutput);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for browsers that block clipboard without HTTPS
      try {
        const ta = document.createElement('textarea');
        ta.value = cssOutput;
        ta.style.cssText = 'position:fixed;opacity:0';
        document.body.appendChild(ta);
        ta.select();
        document.execCommand('copy');
        document.body.removeChild(ta);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch {
        setPngError('Clipboard write failed. Please select and copy the text manually.');
      }
    }
  };

  const handlePNGDownload = async () => {
    setPngLoading(true);
    setPngError('');
    const node = buildPNGNode(colors, roles);
    document.body.appendChild(node);
    try {
      const SWATCH_W   = 120;
      const SWATCH_GAP = 20;
      const PADDING    = 20;
      const totalW     = colors.length * (SWATCH_W + SWATCH_GAP) - SWATCH_GAP + PADDING * 2;

      const canvas = await html2canvas(node, {
        scale:           2,
        backgroundColor: '#f5f2ed',
        width:           totalW,
        height:          260,
        logging:         false,
      });
      const url = canvas.toDataURL('image/png');
      const a   = document.createElement('a');
      a.href     = url;
      a.download = 'palette-studio-swatches.png';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    } catch (e) {
      setPngError(
        'Image generation failed. ' +
        (e.message || 'Please try again, or take a screenshot as an alternative.')
      );
    } finally {
      // Always clean up the hidden node
      document.body.removeChild(node);
      setPngLoading(false);
    }
  };


  const handleTailwindCopy = async () => {
    const twOutput = generateTailwindConfig(colors, roles, scales);
    try {
      await navigator.clipboard.writeText(twOutput);
      setTwCopied(true);
      setTimeout(() => setTwCopied(false), 2000);
    } catch {
      try {
        const ta = document.createElement('textarea');
        ta.value = twOutput;
        ta.style.cssText = 'position:fixed;opacity:0';
        document.body.appendChild(ta);
        ta.select();
        document.execCommand('copy');
        document.body.removeChild(ta);
        setTwCopied(true);
        setTimeout(() => setTwCopied(false), 2000);
      } catch { /* clipboard unavailable */ }
    }
  };
  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

      {/* ── Card 1: PDF Brand Guide ─────────────────────────────────────── */}
      <ExportCard
        title="PDF Brand Guide"
        description="A complete one-page PDF with your colour swatches, values, roles, and health score — ready to share with a designer or client."
      >
        {/* Preview of what's inside */}
        <div
          style={{
            background:          'var(--ps-bg-subtle)',
            border:              '1px solid var(--ps-border)',
            borderRadius:        'var(--ps-radius-lg)',
            padding:             '12px 14px',
            display:             'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
            gap:                 6,
          }}
        >
          {[
            'Header with "Palette Studio" and date',
            `Health score bar (${score}/100)`,
            `${colors.length} colour swatch${colors.length !== 1 ? 'es' : ''} with hex, RGB, HSL`,
            'Assigned role badges',
            '60-30-10 proportion strip',
            issues.filter(i => i.type !== 'info').length > 0
              ? `${issues.filter(i => i.type !== 'info').length} issues listed`
              : 'No issues to list ✓',
          ].map((item, i) => (
            <div
              key={i}
              style={{
                fontFamily: 'var(--ps-font-ui)',
                fontSize:   'var(--ps-text-xs)',
                color:      'var(--ps-text-secondary)',
                display:    'flex',
                alignItems: 'center',
                gap:        5,
              }}
            >
              <span style={{ color: 'var(--ps-success)', fontWeight: 700 }}>✓</span>
              {item}
            </div>
          ))}
        </div>

        <ActionBtn
          onClick={handlePDFDownload}
          loading={pdfLoading}
          loadingLabel="Generating PDF…"
          error={pdfError}
        >
          ↓ Download PDF
        </ActionBtn>
      </ExportCard>

      {/* ── Card 2: CSS Variables ───────────────────────────────────────── */}
      <ExportCard
        title="CSS Variables"
        description="Copy your palette as CSS custom properties, ready to paste into any website or design system."
      >
        {/* Code preview */}
        <pre
          style={{
            background:    '#18181B',
            color:         '#e4e4e7',
            borderRadius:  'var(--ps-radius-lg)',
            padding:       '14px 16px',
            fontSize:      11,
            lineHeight:    1.6,
            overflowX:     'auto',
            overflowY:     'auto',
            maxHeight:     240,
            margin:        0,
            fontFamily:    'var(--ps-font-mono)',
            whiteSpace:    'pre',
            letterSpacing: '.02em',
          }}
        >
          {cssOutput}
        </pre>

        <button
          onClick={handleCopy}
          style={{
            background:    copied ? 'var(--ps-success)' : 'var(--ps-accent)',
            color:         'var(--ps-accent-text)',
            border:        'none',
            borderRadius:  'var(--ps-radius-md)',
            padding:       '9px 20px',
            fontFamily:    'var(--ps-font-ui)',
            fontSize:      'var(--ps-text-sm)',
            fontWeight:    500,
            cursor:        'pointer',
            letterSpacing: '.02em',
            transition:    'background .2s',
            alignSelf:     'flex-start',
          }}
          onMouseEnter={e => { if (!copied) e.currentTarget.style.background = 'var(--ps-accent-hover)'; }}
          onMouseLeave={e => { if (!copied) e.currentTarget.style.background = 'var(--ps-accent)'; }}
        >
          {copied ? '✓ Copied!' : 'Copy to Clipboard'}
        </button>
      </ExportCard>

      {/* ── Card 3: PNG Swatch Sheet ────────────────────────────────────── */}
      <ExportCard
        title="PNG Swatch Sheet"
        description="A clean image of your palette — useful for Slack, presentations, and sharing with non-designers."
      >
        {/* Live mini-preview of what the PNG will look like */}
        <div
          style={{
            background: 'var(--ps-bg-subtle)',
            borderRadius: 'var(--ps-radius-lg)',
            padding:    '14px 16px',
            display:    'flex',
            alignItems: 'flex-end',
            gap:        12,
            overflowX:  'auto',
            border:     '1px solid var(--ps-border)',
          }}
        >
          {colors.map((hex, i) => {
            const role    = roles[hex];
            const roleCol = role ? (ROLE_COL[role] || 'var(--ps-text-secondary)') : 'var(--ps-text-tertiary)';
            return (
              <div key={i} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', flexShrink: 0 }}>
                <div
                  style={{
                    width:        60,
                    height:       60,
                    borderRadius: 'var(--ps-radius-md)',
                    background:   hex,
                    border:       '1px solid rgba(0,0,0,.08)',
                    marginBottom: 5,
                  }}
                />
                <div
                  style={{
                    fontFamily:    'var(--ps-font-mono)',
                    fontSize:      8,
                    fontWeight:    500,
                    color:         'var(--ps-text-primary)',
                    letterSpacing: '.04em',
                  }}
                >
                  {hex.toUpperCase()}
                </div>
                <div
                  style={{
                    fontFamily:    'var(--ps-font-ui)',
                    fontSize:      7,
                    fontWeight:    700,
                    color:         roleCol,
                    letterSpacing: '.06em',
                  }}
                >
                  {role ? role.toUpperCase() : 'UNASSIGNED'}
                </div>
              </div>
            );
          })}
        </div>
        <div
          style={{
            fontFamily: 'var(--ps-font-ui)',
            fontSize:   'var(--ps-text-xs)',
            color:      'var(--ps-text-tertiary)',
            fontStyle:  'italic',
          }}
        >
          PNG exports at 2× resolution (retina quality).
        </div>

        <ActionBtn
          onClick={handlePNGDownload}
          loading={pngLoading}
          loadingLabel="Generating PNG…"
          error={pngError}
        >
          ↓ Download PNG
        </ActionBtn>
      </ExportCard>

      {/* ── Card 4: Tailwind Config ─────────────────────────────────────── */}
      <ExportCard
        title="Tailwind CSS Config"
        description="Add your palette to tailwind.config.js. Includes the full tint & shade scale for each colour."
      >
        <pre
          style={{
            background:    '#18181B',
            color:         '#e4e4e7',
            borderRadius:  'var(--ps-radius-lg)',
            padding:       '14px 16px',
            fontSize:      11,
            lineHeight:    1.6,
            overflowX:     'auto',
            overflowY:     'auto',
            maxHeight:     240,
            margin:        0,
            fontFamily:    'var(--ps-font-mono)',
            whiteSpace:    'pre',
            letterSpacing: '.02em',
          }}
        >
          {generateTailwindConfig(colors, roles, scales)}
        </pre>

        <button
          onClick={handleTailwindCopy}
          style={{
            background:    twCopied ? 'var(--ps-success)' : 'var(--ps-accent)',
            color:         'var(--ps-accent-text)',
            border:        'none',
            borderRadius:  'var(--ps-radius-md)',
            padding:       '9px 20px',
            fontFamily:    'var(--ps-font-ui)',
            fontSize:      'var(--ps-text-sm)',
            fontWeight:    500,
            cursor:        'pointer',
            letterSpacing: '.02em',
            transition:    'background .2s',
            alignSelf:     'flex-start',
          }}
          onMouseEnter={e => { if (!twCopied) e.currentTarget.style.background = 'var(--ps-accent-hover)'; }}
          onMouseLeave={e => { if (!twCopied) e.currentTarget.style.background = 'var(--ps-accent)'; }}
        >
          {twCopied ? '✓ Copied!' : 'Copy to Clipboard'}
        </button>
      </ExportCard>

      {/* ── Design Tokens section ──────────────────────────────────────── */}
      <div style={{ marginTop: 8 }}>
        <ExportTokensTab colors={colors} roles={roles} selectedFont={selectedFont} />
      </div>

      {/* ── Platform-specific export guides ────────────────────────────── */}
      <div style={{ marginTop: 8 }}>
        <PlatformExportSection colors={colors} roles={roles} />
      </div>

    </div>
  );
}
